
import React from 'react';
import { useSearchParams } from 'react-router-dom';
import { ArrowLeft, Bot } from 'lucide-react';
import { BLOG_POSTS } from '../constants';

const Blog: React.FC = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const postId = searchParams.get('id');
  const activePost = BLOG_POSTS.find(p => p.id === postId);

  // Function to handle navigation
  const handlePostClick = (id: string) => {
    setSearchParams({ id });
    window.scrollTo(0, 0);
  };

  const handleBack = () => {
    setSearchParams({});
    window.scrollTo(0, 0);
  };

  return (
    <div className="animate-fade-in pt-12 pb-20">
      <div className="max-w-4xl mx-auto">
        
        {/* Detail View */}
        {activePost ? (
          <div>
            <button 
              onClick={handleBack}
              className="group flex items-center text-sm text-anthropic-gray hover:text-anthropic-accent transition-colors mb-8"
            >
              <ArrowLeft size={16} className="mr-1 group-hover:-translate-x-1 transition-transform" />
              Back to Blogs
            </button>

            <article className="animate-fade-in">
              <div className="flex flex-wrap items-center gap-4 mb-6">
                <span className="text-anthropic-accent font-mono text-sm tracking-wide">{activePost.date}</span>
                {activePost.generator && (
                  <span className="flex items-center gap-1.5 px-2 py-0.5 bg-anthropic-stone/50 rounded-full text-xs font-medium text-anthropic-text/70 border border-anthropic-text/5">
                    <Bot size={12} />
                    Generated by {activePost.generator}
                  </span>
                )}
              </div>
              
              <h1 className="text-3xl md:text-5xl font-serif text-anthropic-text mb-10 leading-tight">
                {activePost.title}
              </h1>
              
              <div className="prose prose-lg max-w-none text-anthropic-gray font-light leading-relaxed whitespace-pre-line border-t border-anthropic-text/10 pt-10">
                {activePost.content.split('\n').map((paragraph, idx) => {
                  // Check if paragraph is the disclaimer (starts with *This blog)
                  if (paragraph.trim().startsWith('*This blog')) {
                    return (
                      <div key={idx} className="bg-anthropic-stone/30 p-6 rounded-lg border border-anthropic-text/5 mb-8">
                        <p className="text-sm text-anthropic-text/80 italic m-0">
                          {paragraph.replace(/\*/g, '')}
                        </p>
                      </div>
                    );
                  }
                  return paragraph.trim() && <p key={idx} className="mb-6">{paragraph}</p>;
                })}
              </div>
            </article>
          </div>
        ) : (
          /* Directory View */
          <div>
            <h1 className="text-4xl md:text-5xl font-serif font-light mb-8 text-anthropic-text">Thoughts & Updates</h1>
            <p className="text-xl font-sans font-light text-anthropic-gray mb-16 max-w-2xl">
              Musings on alignment theory, life at Rutgers, and research updates.
            </p>

            <div className="border-t border-anthropic-text/10">
              {BLOG_POSTS.length > 0 ? (
                <div className="divide-y divide-anthropic-text/10">
                  {BLOG_POSTS.map((post) => (
                    <div 
                      key={post.id} 
                      onClick={() => handlePostClick(post.id)}
                      className="group py-8 cursor-pointer hover:bg-anthropic-stone/20 -mx-4 px-4 rounded-lg transition-colors duration-200"
                    >
                      <div className="flex flex-col md:flex-row md:items-baseline gap-2 md:gap-8">
                        <div className="w-32 flex-shrink-0">
                          <span className="text-anthropic-gray/60 font-mono text-sm">{post.date}</span>
                        </div>
                        <div className="flex-grow">
                          <h3 className="text-2xl font-serif text-anthropic-text group-hover:text-anthropic-accent transition-colors mb-2">
                            {post.title}
                          </h3>
                          <div className="flex items-center gap-2">
                            {post.generator && (
                              <span className="inline-flex items-center gap-1 text-xs text-anthropic-gray/50 uppercase tracking-wider">
                                <Bot size={12} />
                                {post.generator}
                              </span>
                            )}
                          </div>
                        </div>
                        <div className="hidden md:block text-anthropic-gray/30 group-hover:text-anthropic-accent transform group-hover:translate-x-2 transition-all">
                          →
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-20 bg-anthropic-stone/20 rounded-lg border border-dashed border-anthropic-text/10 mt-8">
                  <p className="text-anthropic-gray font-serif text-lg italic">
                    "Research is formalized curiosity. It is poking and prying with a purpose."
                  </p>
                  <p className="text-sm text-anthropic-gray/60 mt-4 font-sans uppercase tracking-widest">
                    Content coming soon
                  </p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Blog;
